// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUYbaYUmhWTGgVudQLOMqFBtr0OYjmeHs',
    appId: '1:119600048653:web:fb916fbffdc458a9e38344',
    messagingSenderId: '119600048653',
    projectId: 'hu-student-debt',
    authDomain: 'hu-student-debt.firebaseapp.com',
    storageBucket: 'hu-student-debt.firebasestorage.app',
    measurementId: 'G-ZEY534H7H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh0P-6P7pzCPIg1KXjK8M8lXwRaGePqJU',
    appId: '1:119600048653:android:b90e76f03dcc7adde38344',
    messagingSenderId: '119600048653',
    projectId: 'hu-student-debt',
    storageBucket: 'hu-student-debt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgBnxnkN7HLfBvVpksuCKTJagMUF_g-mY',
    appId: '1:119600048653:ios:58fad24e8b2e1f97e38344',
    messagingSenderId: '119600048653',
    projectId: 'hu-student-debt',
    storageBucket: 'hu-student-debt.firebasestorage.app',
    iosClientId:
        '119600048653-f0vp2vfih0sq7r4vmbfga7i23reamhqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentDebtApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgBnxnkN7HLfBvVpksuCKTJagMUF_g-mY',
    appId: '1:119600048653:ios:58fad24e8b2e1f97e38344',
    messagingSenderId: '119600048653',
    projectId: 'hu-student-debt',
    storageBucket: 'hu-student-debt.firebasestorage.app',
    iosClientId:
        '119600048653-f0vp2vfih0sq7r4vmbfga7i23reamhqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentDebtApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUYbaYUmhWTGgVudQLOMqFBtr0OYjmeHs',
    appId: '1:119600048653:web:ef3209c3aee62928e38344',
    messagingSenderId: '119600048653',
    projectId: 'hu-student-debt',
    authDomain: 'hu-student-debt.firebaseapp.com',
    storageBucket: 'hu-student-debt.firebasestorage.app',
    measurementId: 'G-FEQH6NBNYZ',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCUYbaYUmhWTGgVudQLOMqFBtr0OYjmeHs',
    appId: '1:119600048653:web:ef3209c3aee62928e38344',
    messagingSenderId: '119600048653',
    projectId: 'hu-student-debt',
    authDomain: 'hu-student-debt.firebaseapp.com',
    storageBucket: 'hu-student-debt.firebasestorage.app',
    measurementId: 'G-FEQH6NBNYZ',
  );
}
